# Generated by Django 5.0.4 on 2024-05-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bells_main', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bell',
            name='audio_file',
            field=models.FileField(blank=True, default=None, upload_to='media/bell_sounds/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='bell',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media/bell_images/%Y/%m/%d/'),
        ),
    ]
