version: "3.11"
   
services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db:/root/db
    environment:
      - SQLITE3_DB=db.sqlite3
  web:
    build: .
    command: python3.11 manage.py runserver 172.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db